name: videodiff
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - ld_impl_linux-64=2.39
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libnsl=2.0.0
  - libsqlite=3.40.0
  - libuuid=2.32.1
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.0.7
  - pip=22.3.1
  - python=3.8.13
  - readline=8.1.2
  - setuptools=65.5.1
  - sqlite=3.40.0
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.2.6
  - pip:
    - accelerate==0.24.0
    - addict==2.4.0
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.10.11
    - aiosignal==1.3.1
    - aliyun-python-sdk-core==2.16.0
    - aliyun-python-sdk-kms==2.16.5
    - antlr4-python3-runtime==4.9.3
    - async-timeout==5.0.1
    - attrs==25.3.0
    - blessed==1.22.0
    - certifi==2025.8.3
    - cffi==1.17.1
    - charset-normalizer==3.4.3
    - click==8.1.8
    - colorama==0.4.6
    - contourpy==1.1.1
    - crcmod==1.7
    - cryptography==46.0.2
    - cycler==0.12.1
    - diffusers==0.11.1
    - einops==0.8.1
    - fairscale==0.4.13
    - filelock==3.14.0
    - fonttools==4.57.0
    - frozenlist==1.5.0
    - fsspec==2025.3.0
    - gpustat==1.1.1
    - hf-xet==1.1.10
    - huggingface-hub==0.17.3
    - idna==3.10
    - imageio==2.31.6
    - imageio-ffmpeg==0.4.9
    - importlib_metadata==8.5.0
    - importlib_resources==6.4.5
    - jinja2==3.1.6
    - jmespath==0.10.0
    - joblib==1.4.2
    - jsonlines==4.0.0
    - kiwisolver==1.4.7
    - lazy_loader==0.4
    - lightning-utilities==0.11.9
    - markdown==3.7
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.7.5
    - mdurl==0.1.2
    - mmcv-full==1.7.2
    - mmengine==0.10.7
    - model-index==0.1.11
    - mpmath==1.3.0
    - multidict==6.1.0
    - networkx==3.1
    - numpy==1.24.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-ml-py==13.580.82
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.9.86
    - nvidia-nvtx-cu12==12.1.105
    - omegaconf==2.3.0
    - opencv-python==4.5.5.62
    - opendatalab==0.0.10
    - openmim==0.3.9
    - openxlab==0.1.2
    - ordered-set==4.1.0
    - oss2==2.17.0
    - packaging==24.2
    - pandas==2.0.3
    - pillow==10.0.1
    - platformdirs==4.3.6
    - propcache==0.2.0
    - psutil==7.1.0
    - pycparser==2.23
    - pycryptodome==3.23.0
    - pygments==2.19.2
    - pyparsing==3.1.4
    - python-dateutil==2.9.0.post0
    - pytorch-lightning==2.4.0
    - pytz==2023.4
    - pywavelets==1.4.1
    - pyyaml==6.0.3
    - regex==2024.11.6
    - requests==2.28.2
    - rich==13.4.2
    - rotary-embedding-torch==0.3.5
    - safetensors==0.5.3
    - scikit-image==0.21.0
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - six==1.17.0
    - sympy==1.13.3
    - tabulate==0.9.0
    - taming-transformers==0.0.1
    - termcolor==2.4.0
    - threadpoolctl==3.5.0
    - tifffile==2023.7.10
    - timm==0.9.8
    - tokenizers==0.14.1
    - tomli==2.3.0
    - torch==1.12.1+cu116
    - torchaudio==0.12.1+cu116
    - torchmetrics==1.5.2
    - torchvision==0.13.1+cu116
    - tqdm==4.65.2
    - transformers==4.34.1
    - triton==3.0.0
    - typing_extensions==4.13.2
    - tzdata==2025.2
    - urllib3==1.26.20
    - wcwidth==0.2.14
    - yapf==0.43.0
    - yarl==1.15.2
    - zipp==3.20.2
prefix: ./anaconda3/envs/videodiff

