data_name: "MosMed"
pretrained_model_path: "configs/compress_ratio_8_sd_config"
output_dir: "your_output_dir"
caption_column: null
image_column: "file_name"
image_condition: True
image_encode: "MedSAM"

train_data:
  data_path: "MosMedData/MosMed_data"
  width: 256
  height: 256
  keep_all_cond_prob: 0.1
  drop_all_cond_prob: 0.1
  drop_each_cond_prob: [0.5] # drop for image prior

validation_data:
  labels:
    - "CT-0"
    - "CT-0"
    - "CT-1"
    - "CT-1"
    - "CT-234"
    - "CT-234"

  images:
    - "MosMedData/MosMed_data/study_0122_slice34.png"
    - "MosMedData/MosMed_data/study_0058_slice39.png"
    - "MosMedData/MosMed_data/study_0398_slice37.png"  
    - "MosMedData/MosMed_data/study_0844_slice05.png"
    - "MosMedData/MosMed_data/study_0941_slice24.png"
    - "MosMedData/MosMed_data/study_1017_slice42.png"

learning_rate: 1e-4
lr_scheduler: "cosine"
lr_warmup_steps: 500
train_batch_size: 64
num_workers: 8
num_train_epochs: 200
checkpointing_steps: xxx # set on your own
validation_steps: xxx    # set on your own

seed: 3407
# mixed_precision: fp16
use_8bit_adam: False
gradient_accumulation_steps: 1
gradient_checkpointing: True
