data_name: "TUSC"
pretrained_model_path: "configs/compress_ratio_8_sd_config"
output_dir: "your_output_dir"
caption_column: null
image_column: "file_name"
image_condition: True
image_encode: "MedSAM"

train_data:
  data_path: "TUSC/TUSC_data"
  width: 256
  height: 256
  keep_all_cond_prob: 0.1
  drop_all_cond_prob: 0.1
  drop_each_cond_prob: [0.5] # drop for image prior

validation_data:
  labels:
    - "TR5"
    - "TR5"
    - "TR4"
    - "TR4"
    - "TR2-3"
    - "TR4"
    - "TR2-3"

  images:
    - "TUSC/TUSC_data/Nodule199_106.png"
    - "TUSC/TUSC_data/Nodule204_86.png"
    - "TUSC/TUSC_data/Nodule84_76.png"  
    - "TUSC/TUSC_data/Nodule87_97.png"
    - "TUSC/TUSC_data/Nodule43_16.png"
    - "TUSC/TUSC_data/Nodule68_135.png"
    - "TUSC/TUSC_data/Nodule200_42.png"

learning_rate: 1e-4
lr_scheduler: "cosine"
lr_warmup_steps: 500
train_batch_size: 64
num_workers: 8
num_train_epochs: 200
checkpointing_steps: xxx # set on your own
validation_steps: xxx    # set on your own

seed: 3407
# mixed_precision: fp16
use_8bit_adam: False
gradient_accumulation_steps: 1
gradient_checkpointing: True
